# Generated by Django 5.1.4 on 2025-06-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_student_room'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
